version: "2.0"

services:
  web:
    build: _docker/web
    volumes:
      - ".:/project"
    working_dir: "/project"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: tactic
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: tactic
      MYSQL_DATABASE: tactic
      MYSQL_USER: tactic
      MYSQL_PASSWORD: tactic
  node:
    build: _docker/node
    command: "npm"
    volumes:
      - ".:/project"
    working_dir: "/project"
    environment:
      HOME: /tmp/node
